app = "extreme-competition-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3333"
  HOST = "0.0.0.0"
  NODE_ENV = "production"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
